version: "3.7"

services:
  redis:
    image: "redis"
    ports:
      - "6389:6379"  # 外部端口:内部端口

  mysql8:
    image: "mysql:8"
    ports:
      - "3310:3306"
    command: "--init-file /data/application/init.sql"  # 初始化命令
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "messageboard"
    volumes:
      - ./init.sql:/data/application/init.sql
      
  messageboard:
    build: .  # 使用当前目录下的 Dockerfile
    # 写一个命令，等待 MySQL 和 Redis 启动后再启动
    command: "sh -c 'while ! nc -z mysql8 3306 && ! nc -z redis 6379; do sleep 3; done;'"
    depends_on:
      - mysql8
      - redis
    ports:
      - "8081:8081"